In [14]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
import joblib

In [15]:
df = pd.read_csv('../data/Iris.csv')
df = df.drop(columns=["Id"])
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
from sklearn.preprocessing import LabelEncoder

# Convert target in numbers
le = LabelEncoder()
df["Species"]= le.fit_transform(df["Species"])

In [17]:
X = df.drop(columns=["Species"]).values
y = df["Species"].values

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [19]:
np.amin(X, axis=0)

array([4.3, 2. , 1. , 0.1])

In [20]:
np.amax(X, axis=0)

array([7.9, 4.4, 6.9, 2.5])

In [21]:
X_test[0]

array([5.8, 2.8, 5.1, 2.4])

In [22]:
y_test[0]

2

In [23]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.90      1.00      0.95        19
           2       1.00      0.87      0.93        15

    accuracy                           0.96        50
   macro avg       0.97      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [25]:
gnb.predict([X_test[0]])

array([2])

In [26]:
# Persist the model
joblib.dump(gnb, '../models/test_model.pkl')

['../models/test_model.pkl']